function TableClientInfo({ bodyExam }) {
  if (bodyExam) {
    return bodyExam.length === 0 ? (
      <p className="load-list" style={{ display: "none" }}></p>
    ) : (
      <>
        <table className="bodyevaluation-table">
          <thead>
            <tr>
              <th>Data</th>
              <th>Abdominal</th>
              <th>Supra ilíaca</th>
              <th>Tríceps </th>
              <th>Bíceps</th>
              <th>Torácica</th>
              <th>Subescapular</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <input
                  className="input-table"
                  id="AdipometryDateLine1"
                  type="date"
                  value={bodyExam[0].AdipometryDateLine1}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="AbdominalAdipometryLine1"
                  type="text"
                  value={bodyExam[0].AbdominalAdipometryLine1}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="SupraIliacAdipometryLine1"
                  type="text"
                  value={bodyExam[0].SupraIliacAdipometryLine1}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="TricepsAdipometryLine1"
                  type="text"
                  value={bodyExam[0].TricepsAdipometryLine1}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="BicepsAdipometryLine1"
                  type="text"
                  value={bodyExam[0].BicepsAdipometryLine1}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="ToraxAdipometryLine1"
                  type="text"
                  value={bodyExam[0].ToraxAdipometryLine1}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="SubscapularAdipometryLine1"
                  type="text"
                  value={bodyExam[0].SubscapularAdipometryLine1}
                />
              </td>
            </tr>
            <tr>
              <td>
                <input
                  className="input-table"
                  id="AdipometryDateLine2"
                  type="date"
                  value={bodyExam[0].AdipometryDateLine2}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="AbdominalAdipometryLine2"
                  type="text"
                  value={bodyExam[0].AbdominalAdipometryLine2}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="SupraIliacAdipometryLine2"
                  type="text"
                  value={bodyExam[0].SupraIliacAdipometryLine2}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="TricepsAdipometryLine2"
                  type="text"
                  value={bodyExam[0].TricepsAdipometryLine2}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="BicepsAdipometryLine2"
                  type="text"
                  value={bodyExam[0].BicepsAdipometryLine2}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="ToraxAdipometryLine2"
                  type="text"
                  value={bodyExam[0].ToraxAdipometryLine2}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="SubscapularAdipometryLine2"
                  type="text"
                  value={bodyExam[0].SubscapularAdipometryLine2}
                />
              </td>
            </tr>
            <tr>
              <td>
                <input
                  className="input-table"
                  id="AdipometryDateLine3"
                  type="date"
                  value={bodyExam[0].AdipometryDateLine3}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="AbdominalAdipometryLine3"
                  type="text"
                  value={bodyExam[0].AbdominalAdipometryLine3}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="SupraIliacAdipometryLine3"
                  type="text"
                  value={bodyExam[0].SupraIliacAdipometryLine3}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="TricepsAdipometryLine3"
                  type="text"
                  value={bodyExam[0].TricepsAdipometryLine3}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="BicepsAdipometryLine3"
                  type="text"
                  value={bodyExam[0].BicepsAdipometryLine3}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="ToraxAdipometryLine3"
                  type="text"
                  value={bodyExam[0].ToraxAdipometryLine3}
                />
              </td>
              <td>
                <input
                  className="input-table"
                  id="SubscapularAdipometryLine3"
                  type="text"
                  value={bodyExam[0].SubscapularAdipometryLine3}
                />
              </td>
            </tr>
          </tbody>
        </table>
      </>
    );
  }
}

export default TableClientInfo;
