function Table() {
  return (
    <table className="bodyevaluation-table">
      <thead>
        <tr>
          <th>Data</th>
          <th>Abdominal</th>
          <th>Supra ilíaca</th>
          <th>Tríceps </th>
          <th>Bíceps</th>
          <th>Torácica</th>
          <th>Subescapular</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <input
              className="input-table"
              id="AdipometryDateLine1"
              type="date"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="AbdominalAdipometryLine1"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="SupraIliacAdipometryLine1"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="TricepsAdipometryLine1"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="BicepsAdipometryLine1"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="ToraxAdipometryLine1"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="SubscapularAdipometryLine1"
              type="text"
            />
          </td>
        </tr>
        <tr>
          <td>
            <input
              className="input-table"
              id="AdipometryDateLine2"
              type="date"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="AbdominalAdipometryLine2"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="SupraIliacAdipometryLine2"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="TricepsAdipometryLine2"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="BicepsAdipometryLine2"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="ToraxAdipometryLine2"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="SubscapularAdipometryLine2"
              type="text"
            />
          </td>
        </tr>
        <tr>
          <td>
            <input
              className="input-table"
              id="AdipometryDateLine3"
              type="date"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="AbdominalAdipometryLine3"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="SupraIliacAdipometryLine3"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="TricepsAdipometryLine3"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="BicepsAdipometryLine3"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="ToraxAdipometryLine3"
              type="text"
            />
          </td>
          <td>
            <input
              className="input-table"
              id="SubscapularAdipometryLine3"
              type="text"
            />
          </td>
        </tr>
      </tbody>
    </table>
  );
}

export default Table;
